### ISSUE TITLE
Shouldn't the 'EU - One way Sign' be called 'EU - No Entry' and issue templates suggestion.

### ISSUE THREAD

**Issue by samuelh2005** [Matis-Projects/tismatis-roads#4]
Shouldn't this sign be called 'EU - No Entry'

![image](https://user-images.githubusercontent.com/41990982/200119635-b3161776-0249-40ff-8758-61d26782f969.png)

And maybe have different variations of this sign that point different ways. Maybe have a round base one too?
![image](https://user-images.githubusercontent.com/41990982/200119784-b856698d-1643-4366-9a4d-ed19c9084acb.png)

Also you may configure [issue templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository) instead of providing an [example one](https://github.com/Matis-Projects/tismatis-roads/issues/1). They can provide a better way to organise the issues. Many people may not see the example one provided.

**Comment by tismatis** [comment]
Hi!

I'm not working on that project but i will fix that this weekend ;)

Sorry for the time i take to just read your message, the webhook in my discord was just dead and i didn't receive the notification!

**Comment by tismatis** [comment]
Fixed but i want put new objects before update.

Thanks for your help and good luck for your fork!
